repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v1.4.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-vet
      - id: golint
      - id: go-mod-tidy

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.56.2
    hooks:
      - id: golangci-lint
        args: ["--fast"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
        exclude: "vendor/"

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.76.3
    hooks:
      - id: trufflehog
        args: ["filesystem", "--no-update", "--only-verified"]

