name: Sanitize Expressions in Script

on:
  workflow_dispatch:

jobs:
  sanitize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Create test script with expressions
        run: |
          echo 'echo "Start ${{ inputs.foo }}"' > script.sh
          echo 'echo "Path: ${{ env.PATH }}"' >> script.sh
          cat script.sh
