name: ShellCheck Test

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Run a flawed shell script"
        run: |
          echo Hello $USER

          for file in *.txt
          do
              cat $file
          done

          if [ $1 == "test" ]
          then
              echo You are testing
          fi

          rm -rf $2

          VAR=hello world

          let count=$count+1

          exit 0
